### ISSUE TITLE
Release 0.3.1

### ISSUE THREAD

**Issue by bollwyvl** [robots-from-jupyter/robotframework-jupyterlibrary#39]
- [x] blockers
  - [x] #38 fix docs build
  - [x] #33 mystnb/pydata-sphinx-theme
  - [x] #36 add some backwards-compatible options for interacting with multiple notebooks in Lab
  - [x] #37 add some more `timeout` args
    - [x] maybe add some more in some places where we hard-code them 
- [x] infra
  - [x] resolve envs 
  - [x] validate on binder
  - [x] tag
  - [x] upload
    - [x] pypi
  - [x] postmortem
    - [x] conda-forge
    - [x] update release process notes
